// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  spaces = 31,
  newline = 32,
  Function = 1,
  Identifier = 2,
  TrackExpression = 5,
  MediaId = 7,
  TrackListExpression = 10,
  Number = 14,
  BinaryExpression = 15,
  UnaryExpression = 18,
  Block = 23
