// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,PlayTrack:6, GetTrack:12, GetTrackFromList:18, GetAlbum:22, GetPlaylist:24, GetFunction:26, PlayTrackList:38, Variable:40, Loop:44, End:50}
export const parser = LRParser.deserialize({
  version: 14,
  states: "+^QYQPOOOhQPO'#C}OOQO'#Cw'#CwQYQPOOOmQPO'#D_OrQPO'#DaOwQPO'#C}O|QPO'#C}OOQO,59i,59iOOQO-E6u-E6uO!RQPO,59yO!WQPO'#DbO!iQPO,59{O!nQPO'#DOO!yQPO,59iO#OQPO'#D^O#^QPO1G/eOOQO'#Cm'#CmO$aQPO,59|O!WQPO'#D]O!WQPO'#CnOOQO'#Cn'#CnOOQO'#DV'#DVOOQO1G/g1G/gO$hQPO'#CsOOQO'#Ca'#CaO$yQPO,59jO%OQPO'#CaO%TQPO'#CaOOQO1G/T1G/TOOQO'#Cf'#CfO%YQPO,59xO%OQPO'#CfO%_QPO'#CfO$OQPO'#CkO%dQPO'#D`OOQO7+%P7+%PO%OQPO'#D`O%TQPO'#D`O%_QPO'#D`OOQO'#Cl'#ClO!WQPO,59VO!WQPO,59VO%xQPO1G/hO%}QPO,59wO&UQPO,59YO&pQPO,59_OOQO,59_,59_OOQO1G/U1G/UO'RQPO'#DPOOQO,58{,58{O#OQPO'#DROOQO1G/d1G/dOOQO,59Q,59QO'RQPO'#DSOOQO,59z,59zOOQO1G.q1G.qO'ZQPO1G.qO'uQPO7+%SOOQO1G/c1G/cOOQO1G.y1G.yOOQO'#DQ'#DQO'zQPO,59kO(PQPO,59mO(UQPO,59nOOQO<<Hn<<HnOOQO1G/V1G/VO!WQPO1G/XOOQO1G/Y1G/YO!WQPO1G/YO(^QPO7+$sO(eQPO'#DUO(oQPO7+$tOOQO<<H_<<H_O!WQPO'#CxO(tQPO,59pOOQO<<H`<<H`O(|QPO,59dOOQO-E6v-E6v",
  stateData: ")W~OoOSpOS~ORUOcVOdSOfTO~OjWO~OQYO~OSZO~OS]O~OS_O~Oe`O~OQfOScO^fO}aO!OaO~OhhO~OQiOUkOXlO~OjmO~OQnOZpO[pO]qO~OQsOScOUuOXvOZuO[uO]wO^sO}aO!OaO~OzxO{xO|xO}aO!OaO~Ow{O~P$OORUOcVOdSOfTOi!PO~OW!QO~OS!RO~OS!TO~OW!UO~OS!WO~Oj!SXzyX{yX|yX}yX!OyX~OQ![O~OW!]O~P$OOzxO{xO|xOwba}ba!ObajbaWba~ORUOcVOdSOfTOi!^O~OQ!_OV!_O~OzxO{xO|xOw_i}_i!O_ij_iW_i~OW!cO~OW!dO~Ow!eO~OW!fOw!gO~OW!kO~P$OOw!lOWxX~P$OOW!nO~Ow!lOWxa~OWlawla~P$OO",
  goto: "%p!VPPPPP!WPPPP!ZPPPP!a!n!x!aPPPP#]PPP#`#jPPPP#p#v#y$S$Y$`P$f$iPPPPP%U%a%d%j%d%mRj]Qo_R!a!T`fZcdyz!e!g!lRs`aybr|}!Z!h!i!obdZ`cdyz!e!g!l]zbr|!h!i!oRg[QROSXR!OR!OhQ!m!iR!p!mXQORh!OR^UQ!SkQ!VpR!XuQ!`!RR!b!WQ!SlR!XvQ!VqR!XwR!j!gQbZQr`Q|cQ}dQ!YyQ!ZzQ!h!eQ!i!gR!o!lceZ`cdyz!e!g!lR^VXPORh!ORt`R[T",
  nodeNames: "⚠ Function Identifier PlayTrack ( TrackExpression GetTrack MediaId ) GetTrackFromList TrackListExpression GetAlbum GetPlaylist GetFunction Number BinaryExpression ArithOp ArithOp UnaryExpression PlayTrackList Variable = Loop Block : End ;",
  maxTerm: 52,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "%c~ReXY!dYZ!uZ[!d]^!upq!drs!zuv#rxy#wyz#|z{$R{|$W|}$]}!O$b!P!Q$g!Q![$l![!]$t!]!^$y!_!`%O!c!}%T#T#o%T$f$g!d~!iSo~XY!dZ[!dpq!d$f$g!d~!zOp~~!}S}!O#Z!Q![#Z!c!}#Z#T#o#Z~#^Trs#m}!O#Z!Q![#Z!c!}#Z#T#o#Z~#rOV~~#wO|~~#|OS~~$ROW~~$WO{~~$]O}~~$bOw~~$gO!O~~$lOz~~$qP^~!Q![$l~$yOh~~%OOj~~%TOe~~%YRQ~!Q![%T!c!}%T#T#o%T",
  tokenizers: [0],
  topRules: {"Function":[0,1]},
  // @ts-ignore
  specialized: [{term: 2, get: (value: any) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
